version: '2'
services:

  misp:
    build: ehttps://github.com/xme/misp-docker.git#master
    environment:
      - MYSQL_ROOT_PASSWORD=Optiv@dm1n
      - MYSQL_MISP_PASSWORD=Optiv@dm1n
      - MYSQL_HOST=misp-db
      - MISP_ADMIN_EMAIL=info@optivmss.com
      - MISP_ADMIN_PASSPHRASE=Optiv@dm1n
      - MISP_BASEURL=http:\/\/misp\.aiem.portal.optivmss.com
      - POSTFIX_RELAY_HOST=relay.aiem.portal.optivmss.com
      - TIMEZONE=America/Chicago
    volumes:
      - misp-urandom:/dev/random
      - misp-data:/var/www/MISP
    links:
      - misp-db
    labels:
      io.rancher.scheduler.affinity:host_label: hub=1
      
  misp-db:
    image: mysql/mysql-server:latest
    environment:
      - MYSQL_ROOT_PASSWORD=Optiv@dm1n
     volumes:
      - misp-mysql:/var/lib/mysql
    labels:
      io.rancher.scheduler.affinity:host_label: hub=1

  yeti:
    image: cogniteev/oracle-java
    labels:
      io.rancher.scheduler.affinity:host_label: hub=1
