version: '2'
services:

  misp:
    image: harvarditsecurity/misp
    environment:
      - MYSQL_ROOT_PASSWORD=Optiv@dm1n
      - MYSQL_MISP_PASSWORD=Optiv@dm1n
      - POSTFIX_RELAY_HOST=relay.aiem.portal.optivmss.com
      - MISP_FQDN=dev-hub.aiem.portal.optivmss.com
      - MISP_EMAIL=info@optivmss.com
    volumes:
     - /dev/urandom:/dev/random
     - /data/misp:/var/www/MISP
     - misp-db:/var/lib/mysql
    depends_on:
     - misp-db
    ports:
    - 80:80
    - 443:443
    - 3306:3306
    labels:
      io.rancher.scheduler.affinity:host_label: hub=1

