version: '2'
services:

  misp:
    build: https://github.com/Betsworth22/docker-misp.git
    volumes:
     - /dev/urandom:/dev/random
     - misp-data:/var/www/MISP
     - mysql-data:/var/lib/mysql
    ports:
    - 80:80
    - 443:443
    - 3306:3306
    labels:
      io.rancher.scheduler.affinity:host_label: hub=1

