version: '2'
services:

 misp-db:
    build: https://github.com/Betsworth22/docker-misp.git#master:container/
    stdin_open: true
    volumes:
    - misp-db:/var/lib/mysql
    tty: true
    command: /init-db
    labels:
      io.rancher.scheduler.affinity:host_label: report=1

 misp:
    build: https://github.com/Betsworth22/docker-misp.git#master:container/
    stdin_open: true
    tty: true
    volumes_from:
    - misp-db
    labels:
      io.rancher.scheduler.affinity:host_label: report=1
      io.rancher.sidekicks: misp-db

