version: '2'
services:

  misp-web:
    depends_on:
      - misp-db
    container_name: misp-web
    hostname: misp
    image: intel-docker:latest
    restart: always
    links:
      - misp-db
    ports:
      - 80:80
    volumes:
      - /dev/urandom:/dev/random
      - misp-data:/var/www/MISP
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=Optiv@dm1n
      - MYSQL_MISP_PASSWORD=Optiv@dm1n
      - MYSQL_HOST=misp-db
      - MISP_ADMIN_EMAIL=admin@optivmss.com
      - MISP_ADMIN_PASSPHRASE=Optiv@dm1n
      - MISP_BASEURL=http://dev-hub.aiem.portal.optivmss.com
      - POSTFIX_RELAY_HOST=relay.aiem.portal.optivmss.com
      - TIMEZONE=America/Chicago
    labels:
      io.rancher.scheduler.affinity:host_label: hub=1

  misp-db:
    container_name: misp-db
    hostname: mysql
    image: mysql/mysql-server:latest
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Optiv@dm1n
    labels:
      io.rancher.scheduler.affinity:host_label: hub=1

