version: '2'
.catalog:
  version: "1.0.0"
  minimum_rancher_version: v1.6.2
  questions:
    - variable: SITE_DNAME
      description: Specify the domain name of the site.
      label: Site domain name
      required: true
      default: projectname.portal.siemonster.com
      type: string
    - variable: BRANCH_NAME
      description: Specify the branch name to checkout.
      label: Branch name
      required: true
      default: master
      type: string

siemonster:
  scale: 1
  retain_ip: true
  version: 1
  health_check:
    port: 80
    interval: 2000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreate
    request_line: GET "/" "HTTP/1.0"
    healthy_threshold: 2
    response_timeout: 2000

msa:
  scale: 1
  retain_ip: true

msa-volume:
  scale: 1
  retain_ip: true

heaven-backend:
  scale: 1
  retain_ip: true