version: '2'
services:
      
  elastic-m01:
    image: sebp/elk
    environment:
      ES_HEAP_SIZE: 4g
      KIBANA_START: 0
      LOGSTASH_START: 0
      MAX_OPEN_FILES: 65536
      TZ: America/Chicago
    volumes:
    - elastic-m01-config:/etc/elasticsearch
    labels:
      io.rancher.scheduler.affinity:host_label: data-1=1
      
  elastic-m02:
    image: sebp/elk
    environment:
      ES_HEAP_SIZE: 4g
      KIBANA_START: 0
      LOGSTASH_START: 0
      MAX_OPEN_FILES: 65536
      TZ: America/Chicago
    volumes:
    - elastic-m02-config:/etc/elasticsearch
    labels:
      io.rancher.scheduler.affinity:host_label: data-3=1
      
  elastic-d01:
    image: sebp/elk
    environment:
      ES_HEAP_SIZE: 16g
      KIBANA_START: 0
      LOGSTASH_START: 0
      MAX_OPEN_FILES: 65536
      TZ: America/Chicago
    volumes:
    - elastic-d01-config:/etc/elasticsearch
    - elastic-d01-data:/var/lib/elasticsearch
    labels:
      io.rancher.scheduler.affinity:host_label: data-2=1
      
  elastic-d02:
    image: sebp/elk
    environment:
      ES_HEAP_SIZE: 16g
      KIBANA_START: 0
      LOGSTASH_START: 0
      MAX_OPEN_FILES: 65536
      TZ: America/Chicago
    volumes:
    - elastic-d02-config:/etc/elasticsearch
    - elastic-d02-data:/var/lib/elasticsearch
    labels:
      io.rancher.scheduler.affinity:host_label: data-4=1
      
  elastic-d03:
    image: sebp/elk
    environment:
      ES_HEAP_SIZE: 16g
      KIBANA_START: 0
      LOGSTASH_START: 0
      MAX_OPEN_FILES: 65536
      TZ: America/Chicago
    volumes:
    - elastic-d03-config:/etc/elasticsearch
    - elastic-d03-data:/var/lib/elasticsearch
    labels:
      io.rancher.scheduler.affinity:host_label: data-5=1
