version: '2'
services:
 
  mysql:
    image: mysql:latest
    environment:
       - MYSQL_ROOT_PASSWORD="MyPassword"
       - MYSQL_DATABASE=gogs
       - MYSQL_USER="username"
       - MYSQL_PASSWORD="MyPassword"
    volumes:
    - mysql-data:/var/lib/mysql/
    labels:
      io.rancher.scheduler.affinity:host_label: repo=1
    tty: true

  gogs:
    image: gogs/gogs:latest
    volumes:
    - gogs-conf:/data/gogs/conf/
    - gogs-data:/app/
    depends_on:
      - mysql
    links:
    - mysql:database
    labels:
      io.rancher.scheduler.affinity:host_label: repo=1
    tty: true
