version: '2'
services:
 
  mysql:
    image: mysql:latest
    environment:
       - MYSQL_ROOT_PASSWORD="RootPassword"
       - MYSQL_DATABASE=gogs
       - MYSQL_USER="mysqluser"
       - MYSQL_PASSWORD="sqluserpassword"
    volumes:
    - mysql-data:/var/lib/mysql/
    labels:
      io.rancher.scheduler.affinity:host_label: repo=1
    tty: true

  gogs:
    image: gogs/gogs:latest
    volumes:
    - gogs-conf:/data
    - gogs-data:/app/
    ports:
    - "port":3000
    - "port":22
    depends_on:
      - mysql
    links:
    - mysql:database
    labels:
      io.rancher.scheduler.affinity:host_label: repo=1
    tty: true
