version: '2'
services:
 
  mysql:
    image: mysql:latest
    environment:
       - MYSQL_ROOT_PASSWORD=7HVTncDdXNbJrFCM
       - MYSQL_DATABASE=gogs
       - MYSQL_USER=optivadmin
       - MYSQL_PASSWORD=BmHrC7qy9qTFQ4cG
    volumes:
    - mysql-data:/var/lib/mysql/
    labels:
      io.rancher.scheduler.affinity:host_label: repo=1
    tty: true

  gogs:
    image: gogs/gogs:latest
    volumes:
    - gogs-conf:/data/gogs/conf/
    - gogs-data:/app/
    ports:
    - 10080:3000
    - 10022:22
    depends_on:
      - mysql
    links:
    - mysql:database
    labels:
      io.rancher.scheduler.affinity:host_label: repo=1
    tty: true
