version: '2'
services:

  siemonster:
    build: https://github.com/siemonster/project-free.git#master
    environment:
      SITE_DNAME: ${SITE_DNAME}
      SITE_NAME: siemonster
      MSA_URL: //msa.${SITE_DNAME}
    volumes:
    - siemonster-data:/root/acembly
    stdin_open: true
    tty: true
    labels:
      io.rancher.scheduler.affinity:host_label_soft: capricorn=1
      io.rancher.container.hostname_override: container_name

  msa:
    build: https://github.com/siemonster/project-free.git#master:containers/msa
    environment:
      ADDITIONAL_PREPARE_COMMAND: 'echo ''db.getCollection("_sites").update({_id:"siemonster"}, {$$set: {names:["msa.${SITE_DNAME}","app.${SITE_DNAME}","admin.${SITE_DNAME}","${SITE_DNAME}"]}})'' | mongo mongo-sites; SITE_NAME=siemonster SITE_DOMAIN=${SITE_DNAME} node update-apps-links.js'
    stdin_open: true
    tty: true
    volumes_from:
    - msa-volume
    labels:
      io.rancher.scheduler.affinity:host_label_soft: capricorn=1
      io.rancher.sidekicks: msa-volume

  msa-volume:
    build: https://github.com/siemonster/project-free.git#master:containers/msa-volume
    stdin_open: true
    tty: true
    volumes:
    - msa-data:/var/lib/mongodb
    command: /bin/bash
    labels:
      io.rancher.scheduler.affinity:host_label_soft: capricorn=1
      io.rancher.container.start_once: 'true'
  
  admin:
    image: ikuturso/msa-free
    environment:
      SITE_NAME: siemonster
      MSA_URL: //msa.${SITE_DNAME}
    stdin_open: true
    tty: true
    labels:
      io.rancher.scheduler.affinity:host_label_soft: capricorn=1
      io.rancher.container.hostname_override: container_name

  heaven-backend:
    image: extremeprog/heaven
    environment:
      DNS_RESOLVER: 169.254.169.250
      SITE_DNAME: ${SITE_DNAME}
      ADDITIONAL_CONFIG: |
        server {
          server_name {{`{{SITE_DNAME}}`}} app.* [a-z0-9-]+\.[a-z0-9-]+\.[a-z]+$$;
          resolver 169.254.169.250 valid=2s ipv6=off;
          set $$hostpass "siemonster";
          location / {
            proxy_pass http://$$hostpass;
            proxy_set_header Accept-Encoding "";
            proxy_set_header Host $$host;
            proxy_set_header X-Real-IP $$remote_addr;
            proxy_set_header Upgrade $$http_upgrade;
            proxy_set_header Connection "upgrade";
          }
        }

        server {
          server_name msa.*;
          resolver 169.254.169.250 valid=2s ipv6=off;
          set $$hostpass "msa";
          location / {
            proxy_pass http://$$hostpass;
            proxy_set_header Accept-Encoding "";
            proxy_set_header Host $$host;
            proxy_set_header X-Real-IP $$remote_addr;
            proxy_set_header Upgrade $$http_upgrade;
            proxy_set_header Connection "upgrade";
          }
        }
        
        server {
          server_name admin.*;
          resolver 169.254.169.250 valid=2s ipv6=off;
          set $$hostpass "admin";
          location / {
            proxy_pass http://$$hostpass;
            proxy_set_header Accept-Encoding "";
            proxy_set_header Host $$host;
            proxy_set_header X-Real-IP $$remote_addr;
            proxy_set_header Upgrade $$http_upgrade;
            proxy_set_header Connection "upgrade";
          }
        }
        
        server {
          server_name interface.*;
          resolver 169.254.169.250 valid=2s ipv6=off;
          set $$hostpass "kibana-d01:5601";
          location / {

            sub_filter </head> '</head><script>window.addEventListener("message", function(event){ if( event.origin.match(/^https?:\/\/(localhost(:\d+)?|(app.)?${SITE_DNAME})/) ) eval(event.data);}, false); if(window == top)top.location = "//${SITE_DNAME}/#/welcome";</script>';
            sub_filter_once on;
            sub_filter_types *;

            proxy_pass http://$$hostpass;
            proxy_set_header Accept-Encoding "";
            proxy_set_header Host $$host;
            proxy_set_header X-Real-IP $$remote_addr;
            proxy_set_header Upgrade $$http_upgrade;
            proxy_set_header Connection "upgrade";
          }
        }
        
        server {
          server_name depot.*;
          resolver 169.254.169.250 valid=2s ipv6=off;
          set $$hostpass "info:8080";
          location / {

            sub_filter </head> '</head><script>window.addEventListener("message", function(event){ if( event.origin.match(/^https?:\/\/(localhost(:\d+)?|(app.)?${SITE_DNAME})/) ) eval(event.data);}, false); if(window == top)top.location = "//${SITE_DNAME}/#/welcome";</script>';
            sub_filter_once on;
            sub_filter_types *;

            proxy_pass http://$$hostpass;
            proxy_set_header Accept-Encoding "";
            proxy_set_header Host $$host;
            proxy_set_header X-Real-IP $$remote_addr;
            proxy_set_header Upgrade $$http_upgrade;
            proxy_set_header Connection "upgrade";
          }
        }
        
        server {
          server_name config.*;
          resolver 169.254.169.250 valid=2s ipv6=off;
          set $$hostpass "gogs:3000";
          location / {

            sub_filter </head> '</head><script>window.addEventListener("message", function(event){ if( event.origin.match(/^https?:\/\/(localhost(:\d+)?|(app.)?${SITE_DNAME})/) ) eval(event.data);}, false); if(window == top)top.location = "//${SITE_DNAME}/#/welcome";</script>';
            sub_filter_once on;
            sub_filter_types *;

            proxy_pass http://$$hostpass;
            proxy_set_header Accept-Encoding "";
            proxy_set_header Host $$host;
            proxy_set_header X-Real-IP $$remote_addr;
            proxy_set_header Upgrade $$http_upgrade;
            proxy_set_header Connection "upgrade";
          }
        }
        
        server {
          server_name incident.*;
          resolver 169.254.169.250 valid=2s ipv6=off;
          set $$hostpass "thehive:9000";
          location / {
            sub_filter </head> '</head><script>window.addEventListener("message", function(event){ if( event.origin.match(/^https?:\/\/(localhost(:\d+)?|(app.)?${SITE_DNAME})/) ) eval(event.data);}, false); if(window == top)top.location = "//${SITE_DNAME}/#/welcome";</script>';
            sub_filter_once on;
            sub_filter_types *;
            proxy_pass http://$$hostpass;
            proxy_set_header Accept-Encoding "";
            proxy_set_header Host $$host;
            proxy_set_header X-Real-IP $$remote_addr;
            proxy_set_header Upgrade $$http_upgrade;
            proxy_set_header Connection "upgrade";
          }
        }
        
        server {
          server_name enrich.*;
          resolver 169.254.169.250 valid=2s ipv6=off;
          set $$hostpass "cortex:9000";
          location / {
            sub_filter </head> '</head><script>window.addEventListener("message", function(event){ if( event.origin.match(/^https?:\/\/(localhost(:\d+)?|(app.)?${SITE_DNAME})/) ) eval(event.data);}, false); if(window == top)top.location = "//${SITE_DNAME}/#/welcome";</script>';
            sub_filter_once on;
            sub_filter_types *;
            proxy_pass http://$$hostpass;
            proxy_set_header Accept-Encoding "";
            proxy_set_header Host $$host;
            proxy_set_header X-Real-IP $$remote_addr;
            proxy_set_header Upgrade $$http_upgrade;
            proxy_set_header Connection "upgrade";
          }
        }
        
        server {
          server_name report.*;
          resolver 169.254.169.250 valid=2s ipv6=off;
          set $$hostpass "skedler:3000";
          location / {
            sub_filter </head> '</head><script>window.addEventListener("message", function(event){ if( event.origin.match(/^https?:\/\/(localhost(:\d+)?|(app.)?${SITE_DNAME})/) ) eval(event.data);}, false); if(window == top)top.location = "//${SITE_DNAME}/#/welcome";</script>';
            sub_filter_once on;
            sub_filter_types *;
            proxy_pass http://$$hostpass;
            proxy_set_header Accept-Encoding "";
            proxy_set_header Host $$host;
            proxy_set_header X-Real-IP $$remote_addr;
            proxy_set_header Upgrade $$http_upgrade;
            proxy_set_header Connection "upgrade";
          }
        }
        
        #server {
        #  server_name ~^(?<service>[^.]+)\.(?<stack>[^.]+)\.[a-z0-9-]+\.[a-z0-9-]+\.[a-z]+$$;
        #  resolver 169.254.169.250 valid=2s ipv6=off;
        #  location / {
        #
        #    sub_filter </head> '</head><script>window.addEventListener("message", function(event){ if( event.origin.match(/^https?:\/\/(localhost(:\d+)?|(app.)?${SITE_DNAME})/) ) eval(event.data);}, false); if(window == top)top.location = "//${SITE_DNAME}/#/welcome";</script>';
        #
        #    proxy_pass http://$$service;
        #    proxy_set_header Accept-Encoding "";
        #    proxy_set_header Host $$host;
        #    proxy_set_header X-Real-IP $$remote_addr;
        #    proxy_set_header Upgrade $$http_upgrade;
        #    proxy_set_header Connection "upgrade";
        #  }
        #}
    stdin_open: true
    tty: true
    labels:
      io.rancher.scheduler.affinity:host_label_soft: capricorn=1
      io.rancher.container.pull_image: always

  info:
    labels:
      io.rancher.scheduler.affinity:host_label_soft: capricorn=1
      io.rancher.container.hostname_override: container_name
    tty: true
    stdin_open: true
    volumes:
    - /opt/containers/${SITE_DNAME}/var/www:/var/www:ro
    image: trinitronx/python-simplehttpserver
