  elasticsearch:
    image: elasticsearch:2
    volumes:
    - dev-threat-data:/usr/share/elasticsearch/data
    command: [
      -Des.script.inline=on,
      -Des.cluster.name=hive,
      -Des.threadpool.index.queue_size=100000,
      -Des.threadpool.search.queue_size=100000,
      -Des.threadpool.bulk.queue_size=1000]
    labels:
      io.rancher.scheduler.affinity:host_label: threat=1

  cortex:
    image: certbdf/cortex:latest
    labels:
      io.rancher.scheduler.affinity:host_label: threat=1

  thehive:
    image: certbdf/thehive:latest
    volumes: 
    - dev-threat-conf:/etc/thehive/application.conf
    ports:
    - 9000:9000
    depends_on:
      - elasticsearch
      - cortex
    labels:
      io.rancher.scheduler.affinity:host_label: threat=1
